name: bar-m-prozessbegleitung
favicon: null
layout_spectrum: 0.75739
typography_spectrum: 0.7658
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ded5cc'
    - '#bda08c'
    - '#947b6b'
    - '#4c352e'
    - '#ce3133'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
